### ISSUE TITLE
picture icon not showing up in 1.8.2, warnings about missing thumbnails (but shows them anyway)

### ISSUE THREAD

**Issue by jmtd** [jneilliii/OctoPrint-PrusaSlicerThumbnails#104]
Thanks for this plugin!

I've found with Octoprint 1.8.2, the following weird results

 * the picture icon never shows up in the file list
 * On pressing "Scan files", the settings dialog throws the following errors

```
   Scan Results
    no_thumbnail
        shoefix_0.2mm_PLA_MINI_33m.gcode 
        ...
        (lists all my gcodes)
 ```

However, if I select "use inline thumbnails", I see inline thumbnails for *all* my gcode files, even though they are listed in the above error.

Side-note: I guess this would be the job for a different plugin, but it would be cool if Octoprint could show the thumbnail on my Prusa Mini when it's printing. At the moment it sents an Octoprint icon so it is possible to show something there. But obviously that'd be a Prusa Mini-specific feature, and this is not a Prusa Mini-specific plugin.

**Comment by jneilliii** [comment]
> Side-note: I guess this would be the job for a different plugin, but it would be cool if Octoprint could show the thumbnail on my Prusa Mini when it's printing.

Unfortunately, that's not possible. For it to show on the Mini the entire file has to be accessible on the SD card of the printer and not sent line at a time. I think Prusa is detecting the file being sent line at a time and shows that logo, and probably does for any host software that is connected to it sending gcode. 

As for your description of the problem, I think I need more details. It's not designed to show up if inline thumbnails is not enabled. Are you saying the picture doesn't show when you click the image button to open the pop-up view?

**Comment by jmtd** [comment]
> Unfortunately, that's not possible. For it to show on the Mini the entire file has to be accessible on the SD card of the printer and not sent line at a time. I think Prusa is detecting the file being sent line at a time and shows that logo, and probably does for any host software that is connected to it sending gcode.

Thanks yes, I read a bit more about it. It seems the Octoprint logo is baked into the Prusa Mini firmware.

> As for your description of the problem, I think I need more details. It's not designed to show up if inline thumbnails is not enabled. Are you saying the picture doesn't show when you click the image button to open the pop-up view?

The *image button* is not showing up. Inline thumbnails seem to work as expected, but the image button is not visible (whether inline thumbnails are on or off)

Thanks!

**Comment by jneilliii** [comment]
Probably a plugin conflict then that is not allowing the button to show when inline thumbnails is disabled. I think GCODE Editor was one of them that has caused this in the past. With inline thumbnail enabled you can click on the image to open the pop-up view.

**Comment by jmtd** [comment]
> Probably a plugin conflict then that is not allowing the button to show when inline thumbnails is disabled.

This is the only plugin I have activated. I have had "Prusa Mini ETA Plugin (0.1.4)" activated in the past but disabled it to test this.

>  With inline thumbnail enabled you can click on the image to open the pop-up view.

Yep that works.

I'm curious how to go about debugging this. Does the plugin log anything somewhere?

**Comment by jneilliii** [comment]
For the UI elements in the file list the only chance of debugging would be if there are errors thrown in the browser's developer tools (F12) on page load.

**Comment by jneilliii** [comment]
```
visible: ($data.thumbnail_src == 
'prusaslicerthumbnails' && $root.settingsViewModel.settings.plugins.prusaslicerthumbnails.inline_thumbnail() == false
```

This is what is setting that visibility. Meaning if this plugin was the one that extracted the file and online thumbnails are not enabled then show the button.
