### ISSUE TITLE
Preview stopped working

### ISSUE THREAD

**Issue by nicktodorov** [jneilliii/OctoPrint-PrusaSlicerThumbnails#106]
After some time working normally, preview pictures stopped loading. There are errors in browser console for missing file. 
With ssh I can see that in the folder there is a png with the same file name as the gcode - test5.png and test5.gcode. But the strange thing is that the error in console says it cannot find a file with date postfix after the name - "http://xxx.xxx.xxx.xxx/downloads/files/local/test5.png?20230331132745"

**Comment by jneilliii** [comment]
This appears to be using the use uploads folder?

**Comment by jneilliii** [comment]
What version of OctoPrint?

**Comment by nicktodorov** [comment]
Sorry for not pointing it - 1.8.7

**Comment by jneilliii** [comment]
weird, I can't seem to reproduce this issue. I just tested on my instance with the option to save images into uploads folder and it definitely generated the image and stored the file, as you can see in my file list screenshot below the png file shows and the button appears to open the preview (with inline thumbnails option disabled). 

![image](https://user-images.githubusercontent.com/5249455/229215515-a8e1b4ba-ac27-4bd9-b46b-26cec445b8b3.png)

**Comment by nicktodorov** [comment]
Sorry for the stupid question, but can you please explain "the option to save images into uploads folder"? Maybe I am missing something?
I can also see the preview button, I can also make it try showing something with inline, the problem is that it is no picture but the question mark icon when a picture is not loaded on a webpage.

**Comment by jneilliii** [comment]
This option:

![image](https://user-images.githubusercontent.com/5249455/229267698-a7971e0b-b296-420f-b518-7efe199add48.png)

**Comment by nicktodorov** [comment]
Ok I have it.
But noticed that scan files button also says no images.
<img width="532" alt="Screenshot 2023-04-01 at 11 08 25" src="https://user-images.githubusercontent.com/25547942/229274297-aafb7488-e058-4c32-91a8-5204458eb2e3.png">

Here is my Cura settings:

<img width="884" alt="Screenshot 2023-04-01 at 11 12 17" src="https://user-images.githubusercontent.com/25547942/229274441-c4d77d14-4058-4e87-b24b-06ac273cffee.png">

And here the beginning of the gcode:

<img width="941" alt="Screenshot 2023-04-01 at 11 13 16" src="https://user-images.githubusercontent.com/25547942/229274464-6cfc313e-65fd-451b-aa49-68edefeca81c.png">

Please, help me figure out what I am doing wrong.

**Comment by jneilliii** [comment]
That option is for a very specific use case of multiple instances sharing the same uploads folder. If you don't have that try disabling the option and uploading a new file and see if things work as expected.

**Comment by nicktodorov** [comment]
Thank you so much!
Yes, after disabling it preview showed up. 
Enhancement proposal: note this specific use somehow in the settings to avoid other users struggling like me in the future?

**Comment by jneilliii** [comment]
It's disabled by default, but yes, documentation does need updating. I'm still confused why it didn't work for you though in the other mode.

**Comment by nicktodorov** [comment]
Fixed.
Thanks again.
