### ISSUE TITLE
Installation without Internet connection fails

### ISSUE THREAD

**Issue by Youras** [jneilliii/OctoPrint-PrusaSlicerThumbnails#108]
Hello, 

Since I have no internet connection on my octoprint, I am installing the plugins with via pluginmanager and uploading the zip file from the plugin.

So far I couldn't get the new versions installed, due to pillow dependency. However, the version 0.4.1 version works well!

Is there a way to make installation possible without internet connection for the new versions as well?

That would be awesome!

Many thanks in advance
Raschid

**Comment by jneilliii** [comment]
in theory you could manually install pillow from source in OctoPrint's venv, but it also has system dependencies that would also probably require internet access to install or you would also have to manually install those offline. the pillow dependency was added to support specific extraction methods required for MKS TFT/Lotmaxx thumbnail support and wouldn't be something that I would remove.
