### ISSUE TITLE
Thumbnail Alignment Options

### ISSUE THREAD

**Issue by ruralaccent** [jneilliii/OctoPrint-PrusaSlicerThumbnails#11]
Would it be possible for alignment options to be a dropdown menu or radio buttons etc.? At the moment you have to type in what you want.

Fixed options will negate issues with folk who don't understand html/css commands...and anyone who doesn't use US English spelling for 'centre'!

No immediate hurry, but just a suggestion to avoid confusion/error.

Many thanks.

**Comment by jneilliii** [comment]
Good idea.

**Comment by jneilliii** [comment]
New version released that resolved this issue.
