### ISSUE TITLE
cached thumbnails in `data` folder bloat backups

### ISSUE THREAD

**Issue by lifeisafractal** [jneilliii/OctoPrint-PrusaSlicerThumbnails#120]
when running backups the cached thumbnails can make the backups rather large. As far as I can tell there isn't a good reason to back these up as they can always be regenerated from the gcode. If this is the case, it would be easy to exclude this plugin's whole data folder entry from being backed up with a simple [backup hook](https://docs.octoprint.org/en/master/bundledplugins/backup.html#additional_excludes_hook). I'm happy to open a PR for this, but wanted to see if this is a good course of action before that.

**Comment by jneilliii** [comment]
I would be open to a PR for that feature as long as it's a configurable option that is disabled by default to maintain current behavior.

**Comment by lifeisafractal** [comment]
Sounds great. I'll work on a this and open a PR against this issue when I get it going. Cheers 🍻

**Comment by lifeisafractal** [comment]
Also, thank you so much for all your great work on OctoPrint plugins. It truly makes my 3d printing experience so much better!

**Comment by lifeisafractal** [comment]
I implemented this [here](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/compare/master...lifeisafractal:OctoPrint-PrusaSlicerThumbnails:backup-exclude?expand=1), however after doing that I realized there is already and option in your plugin to use the uploads folder to cache the thumbnails. The backup system already has an option to ignore that folder, so it feels like it's not worth adding more code for something that is already achievable as is. I'm happy to open a PR if that makes sense to you, but otherwise we can close this issue out.

**Comment by jneilliii** [comment]
That option is actually not what I recommend using for most people, it's only there for multiple instance OctoPrint sharing the same uploads folder like on a NAS. Please do open a PR because I think this option could be helpful for others.
