### ISSUE TITLE
Image button is not there

### ISSUE THREAD

**Issue by alanglois97** [jneilliii/OctoPrint-PrusaSlicerThumbnails#128]
Hello,

I use Octoprint and everything is up to date. The thumbnail slicer is installed but i dont have the image button showing... Is it still available? If not, any other options?

Thanks alot

![image](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/assets/173281423/cbafc6e3-5afd-4827-a53b-cd81a1142e03)

**Comment by jneilliii** [comment]
it looks like you have the inline thumbnail option enabled. that makes the button do away.

**Comment by jneilliii** [comment]
based on the broken images shown in the inline option, it seems that the files are missing from where expected. please share screenshot of your settings and upload one of your gcode files here for further investigation. what slicer do you use to generate gcode, etc.?

**Comment by alanglois97** [comment]
Hello, thank you for the quick help!

I am using prusa slicer

Here is a screenshot of my octoprint settings, i disabled the in line option
![image](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/assets/173281423/58dfc9b3-c61c-4bca-bbe2-32619fde5f1b)

Here is another one of my prusa slicer settings, Vignette means thumbnail
![image](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/assets/173281423/6bb96980-b55a-4ee7-8407-0cfea4d6bece)

Yes based on the broken picture icons I feel like it might be the export of the thumbnail from prusa that is not ok but i dont know whats wrong

Thank you for your help
[test thumbnail.zip](https://github.com/user-attachments/files/15902960/test.thumbnail.zip)

**Comment by alanglois97** [comment]
Working, thank you again
