### ISSUE TITLE
Support images using CR

### ISSUE THREAD

**Issue by xZise** [jneilliii/OctoPrint-PrusaSlicerThumbnails#129]
Currently the regex only allows `LF` and `CRLF` as line breaks, while the plugin for Elegoo printers in [Cura](https://github.com/Molodos/ElegooNeptuneThumbnails) and [Prusa-/OrcaSlicer](https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa) uses only `CR`. For example [file-cr.txt](https://github.com/user-attachments/files/17731220/file-cr.txt) is a file created with Cura where I removed everything after the first gcode to reduce file size.

While the regexes already support all three styles of newlines, the file is loaded in `binary`-mode which uses only `LF` as new lines.

As the file is decoded anyway, maybe using `open(gcode_filename, "r", encoding="utf8", errors="ignore")` would be a possible alternative?

**Comment by jneilliii** [comment]
thanks for the solution to the problem. I have just release 1.0.8 that includes your fix.
