### ISSUE TITLE
No image button to toggle thumbnail preview

### ISSUE THREAD

**Issue by lrybak** [jneilliii/OctoPrint-PrusaSlicerThumbnails#17]
Hello, 
First of all thanks for very usefull plugin. Great work. I really appretiate it.

I cannot see the image icon to preview the thumbnail. Thumbnails are being shown all the time.

Running: OctoPrint 1.3.12 running on OctoPi 0.16.0, PrusaSlicerThumbnails 0.0.4
 
![image](https://user-images.githubusercontent.com/5631648/80180334-d2a05180-8602-11ea-9a5a-82225ae8411c.png)

**Comment by jneilliii** [comment]
That means you have inline image option enabled, disable that option in settings and it should show the button.

**Comment by lrybak** [comment]
Yes, you're right. I missed it. Now it works like a charm!
