### ISSUE TITLE
Add thumbnail to State area

### ISSUE THREAD

**Issue by soerup** [jneilliii/OctoPrint-PrusaSlicerThumbnails#19]
![image](https://user-images.githubusercontent.com/1447807/80210146-89b4c100-8633-11ea-998a-569805f71920.png)

Is it possible to also add thumbnail here?

**Comment by jneilliii** [comment]
That might be possible, I'll just have to check to see if the same bindings are available in that panel that are in the file list panel.

**Comment by jneilliii** [comment]
Would it make sense that when you select a file or start the print of the file that it hides the inline thumbnail from the file list or just leave it as is? Or potentially only inject the thumbnail into the state panel when inline images are not enabled? Make all these variations optional in settings?

**Comment by jneilliii** [comment]
@soerup, new version 0.0.5 released that incorporates this as an option, enabled by default.
