### ISSUE TITLE
State thumbnail visibility 

### ISSUE THREAD

**Issue by pooyashahidi** [jneilliii/OctoPrint-PrusaSlicerThumbnails#25]
If the user choose to have the thumbnail in "State" panel while printing and the gcode is located in a folder, the thumbnail disappears when user navigate out of that folder or to another folder
in this example I'm printing a file from "Speaker_Box" folder and when I'm viewing the root folder there is no thumbnail:
![root folder](https://user-images.githubusercontent.com/5418119/80315849-891a5700-87fa-11ea-9401-d3403a842e14.PNG)
</br>
 but if I navigate to the mentioned folder it appears:
![speaker box](https://user-images.githubusercontent.com/5418119/80315887-c848a800-87fa-11ea-8d61-b8e576b77def.PNG)

**Comment by jneilliii** [comment]
Thanks for this. I think I know why it does that. If you switch back to the folder the file is in does the thumbnail show back up?

**Comment by pooyashahidi** [comment]
yes It shows up when you are in the same folder

**Comment by jneilliii** [comment]
This should be fixed in version 0.0.7 that was just released.
