### ISSUE TITLE
Missing image button

### ISSUE THREAD

**Issue by fornellas** [jneilliii/OctoPrint-PrusaSlicerThumbnails#28]
![image](https://user-images.githubusercontent.com/1386232/80952048-ef057080-8df0-11ea-9bb9-5c42e0b22fc9.png)

I installed PrusaSlicer Thumbnails 0.0.7 with Octoprint 1.4.0 and Python 3.6.9, but unfortunately, there's no new image button. I double checked, this gcode **does** have the thumbnail comments at the first few lines. I did not spot any errors on `octoprint.log` as well.

**Comment by jneilliii** [comment]
Was the gcode uploaded before or after the plugin was installed?

**Comment by fornellas** [comment]
After.

**Comment by jneilliii** [comment]
Please download the gcode from octoprint and share here.

**Comment by apphead** [comment]
Same here.  PrusaSlicer Thumbnails 0.0.7 with Octoprint 1.4.0 and Python 2.7.16. 
Thumbnail is displayed in the list though - configured in Themefy as per your instructions...

![image](https://user-images.githubusercontent.com/505490/81013038-ce720080-8e5a-11ea-9104-4a2854374421.png)

Here's the gcode:

[Test Titan Aero hole spacing_0.2mm_PLA_MK3S_16m.txt](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/files/4577393/Test.Titan.Aero.hole.spacing_0.2mm_PLA_MK3S_16m.txt)

**Comment by jneilliii** [comment]
@apphead, different "issue" the thumbnail is displayed inline because you have the inline option enabled in the plugin's settings. @fornellas says he doesn't see either option the button or the inline image. It also appears he's running Python 3, which could be the underlying problem.

**Comment by jneilliii** [comment]
I can confirm this is a python 3 bug @fornellas, I'm looking into it now.

**Comment by apphead** [comment]
@jneilliii I was trying to demonstrate that the gcode is not the issue as the thumb gets displayed in the list. But I also miss the image button (updated image above to reflect that). 
Strangely, I get the following warning in the settings after a scan:
![image](https://user-images.githubusercontent.com/505490/81016270-66261d80-8e60-11ea-8129-398bfb3b4ce4.png)

**Comment by jneilliii** [comment]
I've seen this before with the gcode editor plugin, which apparently you have installed.

**Comment by jneilliii** [comment]
I think I've got this fixed for you @fornellas, just need to merge in the changes and push a release update.

**Comment by apphead** [comment]
You are right about the gcode editor plugin!
I disabled it and rebooted octoprint -> button still missing
I uninstalled and rebooted octoprint -> missing
I re-scanned for thumbs -> missing (but warning disappeared)
I rebooted RPi -> missing
Re-installed gcode editor and rebooted -> missing
Me -> no clue (but still happy with inline thumb

**Comment by jneilliii** [comment]
@apphead, did you uncheck the inline image option in the plugin's settings when you disabled the gcode editor plugin? As mentioned before, the button will not be there if that option is enabled. You can click the inline thumbnail to open the larger view BTW.

**Comment by apphead** [comment]
Hahaha, turns out that the gcode editor is not the culprit. It's either inline thumb or button. How the f"ç* could I miss that. Thanks for pointing it out! All good now

**Comment by fornellas** [comment]
@jneilliii thanks for looking into this.

I manually updated with the zip file (as it seem 0.0.8 is not published yet). I re-scanned the files, and:

![image](https://user-images.githubusercontent.com/1386232/81050243-8f25cd00-8eb7-11ea-89d6-21a6209dc8ec.png)

\o/

**Comment by jneilliii** [comment]
It is published, in those situations you have to go to advanced and force a refresh because the releases are cached.
