### ISSUE TITLE
Running Octoprint in dual setup...

### ISSUE THREAD

**Issue by Snille** [jneilliii/OctoPrint-PrusaSlicerThumbnails#30]
Hi! I'm running multiple instances of Octoprint on the same system to be able to control two printers from the same RPi. I followed [this guide](https://www.youtube.com/watch?v=7Saa1HpLRoM) and all works well. However, for some reason I only see the thumbnail pictures on one of the instances (the one I uploaded the gcode to), So if I upload to my "MK2.5", I only see the thumb there, and a "broken" thumb in the "MK3" instance. I'm using the "same" upload directory on both instances (located on another server). Even though I do a "Scan files", the thumbnail does not show in the "other" instance... Here is a picture example...
![image](https://user-images.githubusercontent.com/1011699/81062498-5e08c500-8ed6-11ea-8028-9b635b9335bb.png)

I don't know if this is fixable. Maybe if the "thumbnail-storage-directory" could be set manually in a configuration option?
The first instance uses : ~/.octoprint/data/prusaslicerthumbnails/
and the second uses: ~/.octoprint2/data/prusaslicerthumbnails/
And that's ok, but the thumbs only get's "created" on upload... ?

**Comment by jneilliii** [comment]
Yeah, not sure if I can fix this unless the data folder is shared between the two.

**Comment by jneilliii** [comment]
Just pinged @foosel and she says this is not a good idea. 

> that's definitely a bad idea uploads folder should never be shared, messes up housekeeping badly
