### ISSUE TITLE
no button no change 0.4 to 1.0

### ISSUE THREAD

**Issue by BioCore01** [jneilliii/OctoPrint-PrusaSlicerThumbnails#35]
I've been trying since vesion 0.4 to 1.0 never had any change in the interface or button.

I've reinstalled and erased all data, including my print files. 
![screenshot 350](https://user-images.githubusercontent.com/65012322/81387185-9860a500-9116-11ea-94f6-041b34694cbe.jpg)
![screenshot 351](https://user-images.githubusercontent.com/65012322/81387254-aca4a200-9116-11ea-876c-e9551a137785.jpg)
![screenshot 352](https://user-images.githubusercontent.com/65012322/81387312-c2b26280-9116-11ea-8d12-729363da776e.jpg)

**Comment by BioCore01** [comment]
my actif plugings are :

Action Command Prompt Support  
Action Commands (0.2)
Announcement Plugin  
Application Keys Plugin  
Backup & Restore  
Core Wizard  
Discovery  
Firmware Updater (1.7.0)
Fullscreen Plugin (0.0.5)
Logging  
Navbar Temperature Plugin (0.14)
OctoPod Plugin (0.2.6)
Pi Support Plugin  
Printer Safety Check  
Prusa ETA override Plugin (0.1.1) 
PrusaSlicer Thumbnails (0.1.0)
Software Update  
Themeify (1.2.2)
Virtual Printer

**Comment by jneilliii** [comment]
Can you share one of your gcode files please?

**Comment by BioCore01** [comment]
downloaded from my octoprint

https://www.swisstransfer.com/d/b4d4a0d1-81dc-49e4-a23f-370fbd340d75

**Comment by BioCore01** [comment]
downloaded from my octoprint

[separation pour graine V1.0_0.3mm_ABS_MK3S_19m.zip](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/files/4599170/separation.pour.graine.V1.0_0.3mm_ABS_MK3S_19m.zip)

**Comment by jneilliii** [comment]
Your gcode doesn't include the thumbnails inside the file, so the plugin can't extract them. Did you update your printer's ini file to include them and restart PrusaSlicer?

https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails#configuration

**Comment by BioCore01** [comment]
Okay, I forgot the most important step.

![screenshot 353](https://user-images.githubusercontent.com/65012322/81450965-cb8d4d80-9183-11ea-9b44-0803894a57cb.jpg)

-->

![screenshot 354](https://user-images.githubusercontent.com/65012322/81450972-cf20d480-9183-11ea-8463-130890042e48.jpg)

--> add the part selected in blue in the .ini file

![screenshot 355](https://user-images.githubusercontent.com/65012322/81451010-d9db6980-9183-11ea-9b27-ca634b65c65a.jpg)

--> reload your slicer and upload your new code

![screenshot 358](https://user-images.githubusercontent.com/65012322/81451265-671ebe00-9184-11ea-8804-d8c3eaf3228b.jpg)

**Comment by BioCore01** [comment]
beautiful, now all working.

![screenshot 357](https://user-images.githubusercontent.com/65012322/81451306-7aca2480-9184-11ea-8352-2d830e0d65e1.jpg)
