### ISSUE TITLE
No button available - maybe due to Canvas Plugin

### ISSUE THREAD

**Issue by bash-t** [jneilliii/OctoPrint-PrusaSlicerThumbnails#38]
I'm running OctoPrint 1.4.0 (@ OctoPi 0.16.0).

Installing PrusaSlicer Thumbnails 0.1.0 doesn't show up the button for displaying the thumbnail:

![image](https://user-images.githubusercontent.com/500752/81811876-9dae5d00-9525-11ea-80b1-b9618c5da3f5.png)

As additional info: I'm running the Canvas Plugin 2.3.3 since I have the Palette2. This plugin also modified the UI, by adding additional information to the file list.

Best regards,
Bastian

**Comment by jneilliii** [comment]
I guess you figured out that you have to modify your printer profile in PrusaSlicer to allow the thumbnail to be included.

**Comment by bash-t** [comment]
Hi jneilliii, you are right. That I figured out immediately after posting this issue.
Forgot to read everything to the bottom.  
Thanks, now it works like a charm! :)
