### ISSUE TITLE
Most recent update removed thumbnails

### ISSUE THREAD

**Issue by KramRevilo** [jneilliii/OctoPrint-PrusaSlicerThumbnails#42]
After the most recent update my thumbnails are intermittently working.

**Comment by KramRevilo** [comment]
Please let me know what information I can provide to help debug this.

**Comment by jneilliii** [comment]
Please provide example gcode files that aren't working. Have you attempted to use the scan files button is the plugin's settings? It would be odd that this would be working intermittently unless some other factor is coming into play. Any other changes besides upgrading to the latest version?.

**Comment by KramRevilo** [comment]
Okay, for some reason the thumbnails did not automatically populate BUT when I re-scanned through the 'scan files' button then it picked them up.  My apologies, I'll close this.
