### ISSUE TITLE
wrong link in octoprint 

### ISSUE THREAD

**Issue by Avatarsia** [jneilliii/OctoPrint-PrusaSlicerThumbnails#45]
when i click on the hompage button where i can download your plugin it leads to this page

 https://github.com/scottrini/OctoPrint-PrusaLevelingGuide

**Comment by jneilliii** [comment]
Thanks for the heads up. That is not expected. Not sure why that is happening. Looking into it.

**Comment by jneilliii** [comment]
Not sure where you are seeing this, all associated links seem correct from here. I searched each of the repositories and don't see the cross over anywhere.

https://github.com/OctoPrint/plugins.octoprint.org/search?q=PrusaLevelingGuide&unscoped_q=PrusaLevelingGuide

https://github.com/scottrini/OctoPrint-PrusaLevelingGuide/search?q=PrusaSlicerThumbnails&unscoped_q=PrusaSlicerThumbnails

https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/search?q=PrusaLevelingGuide&type=Code

**Comment by Avatarsia** [comment]
hmmm i don't know what was wrong, i can't repeat the way without geting to the correct side.
so seems maybe  mistake of mine
