### ISSUE TITLE
Enhancement Request - Scan for thumbnails via API

### ISSUE THREAD

**Issue by gmccauley** [jneilliii/OctoPrint-PrusaSlicerThumbnails#47]
It would be nice to be able to trigger a scan via API from an external program/script.

I often copy gcode files between printers via script and have to go to settings and rescan after each.

**Comment by jneilliii** [comment]
@gmccauley this is already possible, just undocumented. if you do a POST API call to <octoprint_url>/api/plugin/prusaslicerthumbnails with the appropriate API key in the header and the JSON data being submitted is `{command: "crawl_files"}` it will do this for you. Example curl command line below.

```
curl -s -H "Content-Type: application/json" -H "X-Api-Key: YOUR_API_KEY" -X POST -d '{ "command":"crawl_files" }' http://YOUR_OCTOPRINT_SERVER/api/plugin/prusaslicerthumbnails
```
