### ISSUE TITLE
2.3.0 Alpha - any idea where to add thumbnails = 16x16,220x124 ??

### ISSUE THREAD

**Issue by beef76** [jneilliii/OctoPrint-PrusaSlicerThumbnails#51]
trying out the latest alpha version 2.3.0 but not able to get the thumbnails working.
Any idea where to add the settings? Tried already all printer inis without success :-(

thumbnails = 16x16,220x124

**Comment by jneilliii** [comment]
I do not since I personaly use SuperSlicer (more advanced fork of PrusaSlicer, and they have added the thumbnail option to the UI.

**Comment by beef76** [comment]
Got it working now, had to create a new preset first and than as physical printer. 
Had just a physical printer before with the original preset.
