### ISSUE TITLE
PrusaSlicer 2.3 Alpha 2 Plugin dont works

### ISSUE THREAD

**Issue by PhilippeGalid** [jneilliii/OctoPrint-PrusaSlicerThumbnails#52]
Hi Thanks for your hard work,i love your Plugin,in the new PrusaSlicer 2.3 Alpha 2 your Plugin dont works,can you please make a new workaround for thumbnails = 16x16,220x124 because in PrusaSlicer 2.3 the Octoprinter Profil is a Pysical Printer Profil and there is no line with thumbnails ? Thanks

**Comment by jneilliii** [comment]
See  duplicate issue. 

https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/issues/51
