### ISSUE TITLE
Octoprint 1.5.0 update and now PrusaSlicerThumbnails no longer show thumbnails in "State" 

### ISSUE THREAD

**Issue by wdgeek** [jneilliii/OctoPrint-PrusaSlicerThumbnails#56]
Updated two separate Octoprint Pi machines, a MK3s and a Prusa Mini to Octoprint 1.5.0
After the update both machines no longer show thumbnails in State, but does show thumbnails in Files.
I disabled all my installed plugins for my Prusa Mini to see if any of them were interfering with your plug-in but still no thumbnails in the State window.

**Comment by jneilliii** [comment]
Thanks, I've recently noticed that in my 1.5.0 release candidates as well and haven't had a chance to investigate further. I will be looking into it.

**Comment by jneilliii** [comment]
Can you try with the RC version that i had queued up? Copy/paste the URL below into Plugin Manager > Get More > ...from URL and click Install.

```
https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/archive/0.1.3rc2.zip
```

**Comment by wdgeek** [comment]
I noticed the update rc just now. 
Updated it, and got a message that there was an "official" release.
Installed the official release.
Tried it and can also confirm that its working now on my MK3.
THANK YOU.

**Comment by jneilliii** [comment]
Yeah, I rushed the release since this is going to effect a bunch of people. Thanks for confirming.
