### ISSUE TITLE
Thumbnails not available for PrusaSlicer 2.3.0-beta1

### ISSUE THREAD

**Issue by fabnavigator** [jneilliii/OctoPrint-PrusaSlicerThumbnails#58]
I started using the 2.3.0 beta version of PrusaSlicer and lost my nice thumbnails.

**Comment by jneilliii** [comment]
I can't control what Prusa does with the slicer. Are the thumbnails actually getting embedded in the gcode or not?

**Comment by jneilliii** [comment]
I just tested and 2.3.0rc1 worked for me. It did read in my previous setting though. Double-check your printer profile didn't get messed up, on the printer settings tab...

![image](https://user-images.githubusercontent.com/5249455/102693514-2c383a80-41e9-11eb-9d47-f090d1ba7bb1.png)

**Comment by fabnavigator** [comment]
My bad. Sorry.
