### ISSUE TITLE
Change color of Thumbnail

### ISSUE THREAD

**Issue by Vossberger** [jneilliii/OctoPrint-PrusaSlicerThumbnails#59]
Hi,

is there a way to change the Thumbnail color (Brown) to another color ? Or is this question related to Prusa Slicer ?

![Zwischenablage02](https://user-images.githubusercontent.com/44831869/103654347-0ab7ac80-4f66-11eb-9088-4e98d833d4c4.jpg)

**Comment by jneilliii** [comment]
This is totally controlled by the slicer, I have no way of adjusting the colors internal to the plugin.
