### ISSUE TITLE
Actual Printing Thumbnail?

### ISSUE THREAD

**Issue by FlexerJR** [jneilliii/OctoPrint-PrusaSlicerThumbnails#61]
Hi jneilliii,

thanks for your great work on this plugin. I have a tablet on the wall which is showing my smarthome system. Yesterday i did some parsing of the thumbnail urls to get the link to the image of the actual print. That works great and i can now see the thumbnail of the print in my tablet. 

But there is a problem. I can not do a parsing of the thumbnails url in the subfolders. 

Is it possible to have one place for the actual printing thumbnail with is at a fixed place which will be updated when starting a new print even if the print file will be started out of a subfolder?

http://xxx.xxx.xxx.xxx/plugin/prusaslicerthumbnails/thumbnail/Actual/Cube.png?20201229224717

Would be very very nice!!! I show you a picture. 

![C7A20920-C5DE-4CFC-AFF5-6DA820B36471](https://user-images.githubusercontent.com/40354380/105006508-0fd12d00-5a37-11eb-8e12-3e3d2d4ecee0.jpeg)

Best regards

**Comment by jneilliii** [comment]
The relative url to the thumbnail is actually contained within the files metadata. It is a property named thumbnail.

**Comment by FlexerJR** [comment]
I just solved my issue in a other way. you can close this one. But Thanks for your response!

**Comment by FlexerJR** [comment]
Closed by my side
