### ISSUE TITLE
[feature request] Button/menu option to re-sync thumbnails

### ISSUE THREAD

**Issue by mkoistinen** [jneilliii/OctoPrint-PrusaSlicerThumbnails#63]
Thumbnails are not computed, cached nor displayed for files that are added outside of the Octoprint upload process -- for example, by AFPd, Samba, NFS, etc.

It would be nice to be able to click a button or choose a menu option that regenerates/re-syncs the thumbnails' `.metadata.json` and cached thumbnails at will. Ideally, it would trigger off the "Refresh File List" button and affect the current directory.

Looking at some of the other issues, it seems like this could be a solution for some of those too.

**Comment by jneilliii** [comment]
You mean like the one that is in the settings? Really you shouldn't be putting files directly into the uploads folder and put them in the watched folder instead, in which case the plugin will pick those up.
