### ISSUE TITLE
[Feature Request] - Scan files with button or integrate with Refresh List

### ISSUE THREAD

**Issue by FredrikAir** [jneilliii/OctoPrint-PrusaSlicerThumbnails#70]
Hey, 
I transfer my files to the uploads folder via SAMBA, so the thumbnails are not generated unless I go into the plugin itself and scan the files.

Is it possible to integrate this function into the "Refresh Files List" or add a new Scan-Files-button to the files list menu?
![image](https://user-images.githubusercontent.com/82309730/114297661-2f19ac80-9ab2-11eb-88ba-527e94c9decf.png)

**Comment by jneilliii** [comment]
have you ever thought about using samba share for the watched folder instead of the uploads folder? uploads folder shouldn't be copied to directly from what I've seen posted o OctoPrint's issue tracker.

**Comment by FredrikAir** [comment]
Ok, i did not know that.
I setup the watched folder just now and uploads there generates the thumbnails - Great, Thanks =)

**Comment by jneilliii** [comment]
That's great, I'm glad that worked out for you. With that approach all the plugins that utilize file added events will be able to do what they're supposed to. I'll still keep this request open, as I would like to hook the scan files into the refresh button, but currently there are no event hooks I can use within OctoPrint to do it, so would have to be done in an ugly way.

**Comment by alexandrkut** [comment]
Hello!
About "watched" folder instead of the "uploads" folder - 
I have 4 identical printers and it is logical to use a shared folder.
Example - i upload file to watched folder - all printers grab the file.
Then I notice that the file is not correct.
Аfter that I have to go to all printers to delete the file, instead of only deleting it on the shared uploads folder.

The rescan button will be very useful in this case (currently i run api request wicurl on each octoprint).

**Comment by jneilliii** [comment]
Can't you just re-upload the file to watched folder and have it distribute again. All I'm saying is that the approach of putting files directly into the uploads folder is not a supported use case when it comes to octoprint and I've seen where foosel has mentioned this herself.

**Comment by alexandrkut** [comment]
i can reupload. but when i need just delete file?
i will have to delete it on all printers one by one.
" All I'm saying is that the approach of putting files directly into the uploads folder is not a supported" - ok, i understand =)

**Comment by jneilliii** [comment]
Just curious @alexandrkut are you using a shared basedir folder for all your instances or just a shared watched folder?

**Comment by alexandrkut** [comment]
I use shared upload folder.

**Comment by jneilliii** [comment]
New option added with the above commit and part of version 1.0.1rc3. If you want to test it out and verify you can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and update when prompted.

**Comment by alexandrkut** [comment]
Thank you! 
I will test it tomorrow.
