### ISSUE TITLE
Filenames with .gco extensions are not clickable

### ISSUE THREAD

**Issue by ochm** [jneilliii/OctoPrint-PrusaSlicerThumbnails#77]
Hi there,
is it possible to set the same behavior of display bigger picture for files with .gco extension?
Only at .gcode files is possible to display bigger view after click on thumbnail.
Thank you.

**Comment by jneilliii** [comment]
So does the thumbnail show up at all anywhere or is it just the pop-up where it doesn't show?

**Comment by jneilliii** [comment]
I just looked at the code again and realized there are a couple of places that this occurs, definitely a bug. I'll need to adjust the name replacing syntax to allow the shortened extension.

**Comment by jneilliii** [comment]
Issue should be fixed by the above commit. If you'd like to try it out you can copy/paste the URL below into plugin manager > get more > ...from URL and clicking Install.

```
https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/archive/refs/heads/dev.zip
```

**Comment by ochm** [comment]
Great, works! Thank you.
