### ISSUE TITLE
[Feature Request] Please add IdeaMaker Sliser

### ISSUE THREAD

**Issue by CzarnyLew** [jneilliii/OctoPrint-PrusaSlicerThumbnails#87]
Could you add Thumbnails from softwer ideaMaker - 3D Slicer Software (https://www.raise3d.com/ideamaker/)

**Comment by jneilliii** [comment]
Only if the slicer supports embedding thumbnails into gcode. I do not know if it's possible.

**Comment by jneilliii** [comment]
I just downloaded the manual for ideamaker and it looks like there is an option you can enable to let my plugin work.

![image](https://user-images.githubusercontent.com/5249455/153294358-19485721-6ffd-4de2-9a37-eb4f7dc56b18.png)

**Comment by CzarnyLew** [comment]
I had checked this box. Problem was with my browser not refresh and I have not seen the thumbnails.

Now is everything OK

Thank You for quickly acting
