### ISSUE TITLE
Thumbnails not working for subdirs

### ISSUE THREAD

**Issue by KramRevilo** [jneilliii/OctoPrint-PrusaSlicerThumbnails#9]
Had an existing subdir in OctoPrint file structure hosting some old files and when I navigate into this directory none of the line items (separate gcode files) have the icon for the thumbnail.  But works GREAT in main directory.

**Comment by jneilliii** [comment]
Previously uploaded files will not get re-evaluated, so this is expected if they were there prior to the plugin being installed.

**Comment by KramRevilo** [comment]
Ah, understood.
