### ISSUE TITLE
[Feature Request] Support Luban thumbnails

### ISSUE THREAD

**Issue by Rocket78** [jneilliii/OctoPrint-PrusaSlicerThumbnails#91]
Luban is the slicer from Snapmaker and is also embedding thumbnails in gcode files to show them on the touch display. It is preceeded by a ";thumbnail:" comment following a whitespace and a html like formatting of the image data. Should be very easy to implement. I attached a sample:
[3DBenchy_1664841208541.zip](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/files/9701798/3DBenchy_1664841208541.zip)

I also use the Snapmaker 2.0 Cura plugin (https://github.com/macdylan/Snapmaker2Plugin) which could send the  gcode via wifi directly after slicing which also adds the needed info for the touch display including the thumbnail. But as I am using Octoprint most of the time it would be nice to see these thumbnails.

**Comment by jneilliii** [comment]
oh yeah, this would be fairly easy to implement in the plugin. the format is the exact same (base64 encoded png file) but on one line compared to how PrusaSlicer/Cura Thumbnails post processor does it.

**Comment by jneilliii** [comment]
Added with the above commit and available as version 1.0.1rc6. You can change the release channel for the plugin in OctoPrint's Software Update settings to `Release Candidate` and update when prompted to get the changes. Unfortunately the size of the image is pretty tiny.

![image](https://user-images.githubusercontent.com/5249455/193736656-22128fa3-2aba-4668-ad00-d58629540d2f.png)

**Comment by Rocket78** [comment]
Thanks for the fast reply and implementation. The size of the example is 720x480px when I paste the Base64 here https://base64.guru/converter/decode/image which is fairly big imho. Are we talking about the same? The Snapmaker Cura plugin produces 150x150px thumbnails which is also enough for me.

**Comment by jneilliii** [comment]
It could have been the settings I had in my dev environment. I honestly didn't look at the actual extracted png file.
