### ISSUE TITLE
Thumbnails not appearing

### ISSUE THREAD

**Issue by 3dprintrecycling** [jneilliii/OctoPrint-PrusaSlicerThumbnails#94]
I installed Cura 5.2.1 and sliced a file, after uploading it to octoprint no thumbnail appears and there is nowhere for me to click to make one appear. The plugin appears to have otherwise installed correctly.

Thank you

**Comment by jneilliii** [comment]
Did you set the post-processing script in Cura to add the thumbnail?

https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails#cura

**Comment by 3dprintrecycling** [comment]
Hello,

I had not done that but once I set the post processing script it works.

Thank you
